### ISSUE TITLE
Implement Pomises

### ISSUE THREAD

**Issue by mhombach** [wankdanker/node-odbc#48]
Hey,
i want to know if you can implement Promises instead of the callback-style. If this repo is not active anymore or you don't have time to work through pull-requests, i would just fork thes repo and implement my own solution. So... just asking, since i don't want to fork if this can be fixed/implemented here :)

**Comment by markdirish** [comment]
Hi @mhombach ,

I recently took over development of this package and have been working on getting a 2.0.0 version pushed out. In it I have implemented promises for all asynchronous functions (if you don't pass a callback, it will return a promise instead).

Information on the beta can be found here: https://www.npmjs.com/package/odbc/v/2.0.0-beta.0
To install, you will need to add the beta tag: `npm install odbc@beta`

Note that the API has changed from v 1.x, so read the docs at the above npmjs site

**Comment by mhombach** [comment]
Sorry for the long delay, glad to hear and see that promises are available now :)

Thanks for your worke =)
