### ISSUE TITLE
Case sensitive

### ISSUE THREAD

**Issue by ghost** [wankdanker/node-odbc#66]
Is there an option somewhere to enable/disable case sensitive?

Thanks 👍

**Comment by markirish** [comment]
Do you have an example of what you are looking for?

I would assume that this would be a driver or database level option. If you go to Microsoft's ODBC documentation and look up (SQLGetInfo)[https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetinfo-function?view=sql-server-2017], there is an option called `SQL_IDENTIFIER_CASE` which will tell you whether identifiers are case sensitive. But this is read only, and it doesn't appear that you can set it.

In my experience with most DBMS, identifiers are usually case insensitive and convert to uppercase or lowercase, unless they are wrapped in quotes. For example `mYtAbLe` and `myTable` will both be `mytable` to the database, while `mytable` and `"myTable"` will be different.
