### ISSUE TITLE
Setting Local Variables

### ISSUE THREAD

**Issue by sjmorales** [wankdanker/node-odbc#70]
Hi,

Is there a way to do "SET :LOCALVARIABLE = SOME_VALUE" ?

The only work-a-round I could find is to read it as a table with "VALUES (SOME_VALUE)"

I was hoping there was a better way.

Thanks,
Steve

**Comment by markirish** [comment]
Hi Steve,

This seems a little outside the scope of the node `odbc` package, but what DBMS are you running? There is no API call in this package to set a local variable, you will have to do it with a query, and then use it according the restrictions of your DBMS.
