### ISSUE TITLE
Vague error messages

### ISSUE THREAD

**Issue by otang** [wankdanker/node-odbc#81]
Hello. The error messages from ODBC are quite uninformative. SQL syntax errors are very vague and don't describe where the error occurred or hint to what may be the problem.

### Example error
```
Error: [odbc] Error executing the sql statement
```

How can we access more information about the errors?

**Comment by wankdanker** [comment]
Which version are you using?

**Comment by otang** [comment]
version "2.2.2"

**Comment by wankdanker** [comment]
IBM took over development of this module for v2.x.x. You might be able to find more help here: https://github.com/markdirish/node-odbc

And looks like this issue has already been mentioned there: https://github.com/markdirish/node-odbc/issues/43

odbc v1.x.x definitely has helpful error messages. But, the API is totally different.

**Comment by otang** [comment]
@wankdanker ok thanks. Given the importance of error messages we will consider switching to v1.x.x. Are there any major shortcomings of v1 that you are aware of? It seems like an improvement

**Comment by wankdanker** [comment]
Here are the major shortcomings:

* does not work with node after v11
* no promises

v2 was basically a complete rewrite using [n-api](https://nodejs.org/api/n-api.html). 
v1 uses [nan](https://github.com/nodejs/nan) which apparently supports node v12 and v13. But, the module does not currently compile with those versions.

I am still using v1 on all of my projects.

**Comment by otang** [comment]
@wankdanker thank you for this ^

**Comment by otang** [comment]
@wankdanker where can I find the documentation for v1 API?

**Comment by wankdanker** [comment]
https://github.com/wankdanker/node-odbc/tree/v1

**Comment by otang** [comment]
@wankdanker just wanted to let you know that we've successfully "down"graded to v1.4.6 and it's improved the stability and error logging :) Thank you for your help and Happy New Year!

**Comment by wankdanker** [comment]
@otang  You're welcome. Happy New Year!
