### ISSUE TITLE
Error occurs while building the node-odbc modules 

### ISSUE THREAD

**Issue by azzy5** [wankdanker/node-odbc#88]
node -v : 12.18.3
npm -v : 6.14.6
node-gyp -v : v7.1.0
OS: CentOS 7

Not sure if this is the same as #87  but I also noticed few errors while building a module after cloning.

Expected behavior: the module should be built correctly

Actual behavior: the build fails with the following error the complete output is attached):

`../src/odbc.cpp: At global scope:
../src/odbc.cpp:972:26: error: variable or field ‘init’ declared void
 extern "C" void init(v8::Handle<Object> exports) {
                          ^
../src/odbc.cpp:972:22: error: ‘Handle’ is not a member of ‘v8’
 extern "C" void init(v8::Handle<Object> exports) {
                      ^
../src/odbc.cpp:972:39: error: expected primary-expression before ‘>’ token
 extern "C" void init(v8::Handle<Object> exports) {
                                       ^
../src/odbc.cpp:972:41: error: ‘exports’ was not declared in this scope
 extern "C" void init(v8::Handle<Object> exports) {
                                         ^
In file included from ../src/odbc.cpp:20:0:
../src/odbc.cpp:984:28: error: ‘init’ was not declared in this scope
 NODE_MODULE(odbc_bindings, init)
                            ^
/root/.cache/node-gyp/12.18.3/include/node/node.h:608:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^
../src/odbc.cpp:984:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(odbc_bindings, init)
 ^
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
make: Leaving directory `/root/node_build_test/node-odbc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-1062.9.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /root/node_build_test/node-odbc
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok
[node_build_output.txt](https://github.com/wankdanker/node-odbc/files/5109792/node_build_output.txt)

`

**Comment by azzy5** [comment]
@wankdanker  Please let me know if any additional details required.

**Comment by wankdanker** [comment]
@azzy5 If you are still using the odbc@^1.X.X API, then odbc@1.4.10 should work with node v3 through v16, solving this problem.
