### ISSUE TITLE
ODBC version 2.3.5 throwing data overflow error

### ISSUE THREAD

**Issue by Rohit-Parte** [wankdanker/node-odbc#93]
Can somebody please help me with below error, it is occurring on odbc - 2.3.5 version, We cannot move to latest versions due to internal dependencies. Environment is redhat 7 and db is sybase
[
    {
      state: 'HY000',
      code: 30128,
      message: '[SAP][ASE ODBC Driver]Data overflow. ' +
        'Increase specified column size or buffer ' +
        'size'
    }
  ]

**Comment by markirish** [comment]
Hi @Rohit-Parte ,

Version 2.x is managed out of this repository: https://github.com/markdirish/node-odbc

There are instructions on that page on how to get some debugging information: https://github.com/markdirish/node-odbc#debugging

Then when you create an issue, the issue template will prompt you for information that will be helpful in figuring out what your issue it.
